### ISSUE TITLE
trouble rendering values

### ISSUE THREAD

**Issue by ian-luca** [WebReflection/heresy-ssr#21]
When I try to render my page content with heresy-ssr I get the following error: 
_Error: 2 values instead of 0_

I guess somehow the `Tagger` expects `document` as target to have zero `Holes`?
 
**The stacktrace**
    _at /app/node_modules/domtagger/cjs/index.js:63:17
    at /app/node_modules/domtagger/cjs/index.js:103:20
    at unroll (/app/node_modules/lighterhtml/cjs/index.js:68:24)
    at render (/app/node_modules/lighterhtml/cjs/index.js:24:19)
    at render (/app/node_modules/heresy/cjs/index.js:207:33)
    at render (/app/node_modules/heresy-ssr/cjs/index.js:112:9)_

**My application code**
```javascript
import express from "express"
import { document, render, html } from "heresy-ssr"

const app = express()

const lang = "en"
const dynamicScriptPath = "/some/path/to/js-file.js"

function renderIndexPage() {
  render(document, html`
    <html lang=${lang}>
      <head>
        <title>ianluca</title>
        <CustomElements/>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <script src=${dynamicScriptPath}></script>
      </head>
      <body>
      </body>
    </html>`
  )
}

app.get("/", (_, res) => {
  renderIndexPage()

  res.contentType("html")
    .send(document.toString())
})

app.listen(80)
```

**The content delivered by the server**
```html
<!DOCTYPE html>
<html>
    <head>
        <title>ianluca</title>
        <script is="custom-elements"></script>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="-0.757559%"></script>
    </head>
    <body>
    </body>
</html>
```

**Comment by WebReflection** [comment]
This bug was brought to myself via [basicHTML](https://github.com/WebReflection/basicHTML).

I've no idea what's going in there, but I can confirm heresy-ssr is fixed now.
