### ISSUE TITLE
Different ownerDocument

### ISSUE THREAD

**Issue by CaptainJKoB** [WebReflection/heresy-ssr#26]
Hello 👋 

If  you want to use multiple documents for rendering the `ownerDocument` property of the element rendered inside the document always points towards the `document` exported from `heresy-ssr`.
Is there any way to point it towards the newly created document? 

Thanks

Reproduction example:
```js
const http = require('http');
const {Document, document, render, html, define} = require('heresy-ssr');

const doc = new Document;

define({
  name: 'TestElement',
  tagName: 'div',
  onconnected() {
    console.log('isNewDocument', this.ownerDocument === doc);
    console.log('isDefaultDocument', this.ownerDocument === document);
  },
  render() {
    this.html`Hello world!`;
  }
});

render(doc, html`<html><TestElement /></html>`);

console.log('newDocumentToString', doc.toString());
console.log('defaultDocumentToString', document.toString());

const server = http.createServer(function(req, res) {
	res.writeHead(200, {"content-type": "text/html;charset=utf-8"});
	res.end(doc.toString());
}).listen(8080, () => console.log("server running"))
```
Logging output:
```cmd
isNewDocument false
isDefaultDocument true
newDocumentToString <!DOCTYPE html><html><div is="test-element">Hello world!</div></html>
defaultDocumentToString <!DOCTYPE html><html></html>
```

**Comment by WebReflection** [comment]
This is a very ugly limitation of *basicHTML*, which I am planning to deprecate soon and use [linkedom](https://github.com/WebReflection/linkedom#readme) instead, which never needs, nor use, global `document` or global `window` things (although here needed by heresy itself due lighterhtml needing it too).

A workaround is to set the element `ownerDocument` via the `oninit()` callback, but it's an ugly workaround indeed, although it should produce the expected result.

**Comment by CaptainJKoB** [comment]
Okey, thank you for the insight. I will try to workaroud it somehow.
