### ISSUE TITLE
Style is not rendered when using multiple documents

### ISSUE THREAD

**Issue by jinxmcg** [WebReflection/heresy-ssr#6]
When using multiple documents the components style is not rendered in the header

`
const {Document, render, html} = require('heresy-ssr');
const doc = new Document;
`
however when using the default document the components style appears in the header

`
const {document, render, html} = require('heresy-ssr');
`

am I doing something wrong?

Thank you.

**Comment by bcomnes** [comment]
Also `<CustomElements />` just turns into `<script is="custom-elements"></script>` on a new Document instance.  Looking around in the code for hints, but dropping a note here as its likely related.

**Comment by bcomnes** [comment]
A hint from the README:

> global customElements or document, swappable on the window with any local instance of Document or CustomElementRegistry

So I think maybe you have to swap the document on the window object and register things again? Not sure, still playing around.

**Comment by jinxmcg** [comment]
So I guess this is dead...

**Comment by WebReflection** [comment]
So sorry I've just realized for some reason I wasn't watching my own repository ... will take care of this ASAP.

**Comment by WebReflection** [comment]
@bcomnes @jinxmcg both bugs have been fixed, you have styles per each new Document, and also Custom Elements per each new document.

Apologies for the delay.

**Comment by bcomnes** [comment]
Awesome! Will revisit soon.  Should make things easier.

**Comment by jinxmcg** [comment]
Thank you!
